export interface HomeworkQuestion {
  id: string;
  category: "KANJI" | "VOCABULARY" | "GRAMMAR" | "PARTICLES" | "READING";
  questionText: string;
  options: string[];
  correctOption: number;
  explanation: string;
  marks: number;
}

// 15 Curated Comprehensive Questions per JLPT Level (N5 to N1)
const N5_QUESTIONS: HomeworkQuestion[] = [
  // 1-3: Kanji
  {
    id: "q1",
    category: "KANJI",
    questionText: "「山」の正しい読み方はどれですか？",
    options: ["やま", "かわ", "うみ", "もり"],
    correctOption: 0,
    explanation: "「山」は訓読みで「やま」、音読みで「サン」と読みます。",
    marks: 2,
  },
  {
    id: "q2",
    category: "KANJI",
    questionText: "「一、二、三」の次に来る数字の漢字はどれですか？",
    options: ["五", "四", "六", "七"],
    correctOption: 1,
    explanation: "3（三）の次は4で、漢字では「四」と書きます。",
    marks: 2,
  },
  {
    id: "q3",
    category: "KANJI",
    questionText: "文の空欄に入る漢字を選びなさい: 毎朝、___を飲みます。",
    options: ["水", "木", "火", "土"],
    correctOption: 0,
    explanation: "「水（みず）」を飲むのが自然な文脈です。",
    marks: 2,
  },
  // 4-6: Vocabulary
  {
    id: "q4",
    category: "VOCABULARY",
    questionText: "「あした」の反対の意味を持つ言葉はどれですか？",
    options: ["きのう", "きょう", "あさって", "おととい"],
    correctOption: 0,
    explanation: "「あした（明日）」は未来の1日後で、「きのう（昨日）」は過去の1日前です。",
    marks: 2,
  },
  {
    id: "q5",
    category: "VOCABULARY",
    questionText: "部屋が暗いので、電気を_____。",
    options: ["つけました", "消しました", "開けました", "閉めました"],
    correctOption: 0,
    explanation: "暗い部屋を明るくするために電気を「つける（つけました）」と言います。",
    marks: 2,
  },
  {
    id: "q6",
    category: "VOCABULARY",
    questionText: "友達と駅の前で_____をしました。",
    options: ["約束", "宿題", "病気", "掃除"],
    correctOption: 0,
    explanation: "駅前で待ち合わせをする文脈では「約束（やくそく）」が適切です。",
    marks: 2,
  },
  // 7-10: Grammar
  {
    id: "q7",
    category: "GRAMMAR",
    questionText: "図書館では静かに本を_____ください。",
    options: ["読んで", "読む", "読みます", "読まない"],
    correctOption: 0,
    explanation: "丁寧な指示・依頼には「動詞テ形 ＋ ください」を用います。「読む」のテ形は「読んで」です。",
    marks: 2,
  },
  {
    id: "q8",
    category: "GRAMMAR",
    questionText: "このりんごは甘くて_____です。",
    options: ["おいしい", "おいしくない", "おいしかった", "おいしくて"],
    correctOption: 0,
    explanation: "い形容詞を並べる接続では、前の形容詞を「〜くて」にして後に形容詞を続けます。",
    marks: 2,
  },
  {
    id: "q9",
    category: "GRAMMAR",
    questionText: "日本語を話すこと_____上手になりたいです。",
    options: ["が", "を", "に", "で"],
    correctOption: 0,
    explanation: "「上手・下手」の対象を表す助詞は「が」になります。",
    marks: 2,
  },
  {
    id: "q10",
    category: "GRAMMAR",
    questionText: "昨日、デパートへ行って靴を_____。",
    options: ["買いました", "買います", "買う", "買って"],
    correctOption: 0,
    explanation: "「昨日」の過去の動作を表すため、過去形「買いました」を選びます。",
    marks: 2,
  },
  // 11-13: Particles
  {
    id: "q11",
    category: "PARTICLES",
    questionText: "毎朝７時_____起きて、顔を洗います。",
    options: ["に", "で", "を", "へ"],
    correctOption: 0,
    explanation: "特定の時刻に行う動作を表す場合は助詞「に」を用います。",
    marks: 2,
  },
  {
    id: "q12",
    category: "PARTICLES",
    questionText: "私はスプーン_____カレーを食べます。",
    options: ["で", "に", "を", "と"],
    correctOption: 0,
    explanation: "手段や道具を表す助詞は「で」です。",
    marks: 2,
  },
  {
    id: "q13",
    category: "PARTICLES",
    questionText: "東京から京都_____新幹線で２時間半かかります。",
    options: ["まで", "から", "より", "だけ"],
    correctOption: 0,
    explanation: "起点「から」に対して終点を表すのは「まで」です。",
    marks: 2,
  },
  // 14-15: Reading Comprehension
  {
    id: "q14",
    category: "READING",
    questionText: "【短い会話】田中：「明日、一緒に映画を見に行きませんか。」 佐藤：「いいですね、_____。」 空欄に入る自然な返事はどれですか？",
    options: ["行きましょう", "行きません", "行きました", "行ったでしょう"],
    correctOption: 0,
    explanation: "「〜ませんか」という誘いに前向きに応じる時は「〜ましょう」と答えます。",
    marks: 2,
  },
  {
    id: "q15",
    category: "READING",
    questionText: "【短文読解】「私の猫は白くて小さいです。魚がとても好きで、毎日たくさん食べます。」 猫は何が好きですか？",
    options: ["魚", "肉", "野菜", "果物"],
    correctOption: 0,
    explanation: "文章中に「魚がとても好きで」と明確に書かれています。",
    marks: 2,
  },
];

const N4_QUESTIONS: HomeworkQuestion[] = [
  {
    id: "q1",
    category: "KANJI",
    questionText: "「都合」の正しい読み方はどれですか？",
    options: ["つごう", "とごう", "つあい", "ずごう"],
    correctOption: 0,
    explanation: "「都合（つごう）」はスケジュールや状況の良し悪しを表します。",
    marks: 2,
  },
  {
    id: "q2",
    category: "KANJI",
    questionText: "「運動」の「運」と同じ漢字を使う言葉はどれですか？",
    options: ["運ぶ（はこぶ）", "連れる（つれる）", "通る（とおる）", "遊ぶ（あそぶ）"],
    correctOption: 0,
    explanation: "「運」の訓読みは「はこ・ぶ」です。",
    marks: 2,
  },
  {
    id: "q3",
    category: "KANJI",
    questionText: "「試験」の読み方を選びなさい。",
    options: ["しけん", "じけん", "しげん", "しんけん"],
    correctOption: 0,
    explanation: "「試験」は「しけん」と読みます。",
    marks: 2,
  },
  {
    id: "q4",
    category: "VOCABULARY",
    questionText: "道が分からないので、交番で道を_____。",
    options: ["尋ねました", "答えました", "頼みました", "教えました"],
    correctOption: 0,
    explanation: "道をきく行為は「尋ねる（たずねる）」を用います。",
    marks: 2,
  },
  {
    id: "q5",
    category: "VOCABULARY",
    questionText: "風邪をひいたので、薬を飲んで_____休みます。",
    options: ["ゆっくり", "すっかり", "はっきり", "びっくり"],
    correctOption: 0,
    explanation: "十分にくつろいで休息をとる副詞は「ゆっくり」です。",
    marks: 2,
  },
  {
    id: "q6",
    category: "VOCABULARY",
    questionText: "電車に遅れそうだったので、走って駅へ_____。",
    options: ["急ぎました", "届きました", "向かいました", "歩きました"],
    correctOption: 0,
    explanation: "時間を早めるために速く動くことは「急ぐ（急ぎました）」です。",
    marks: 2,
  },
  {
    id: "q7",
    category: "GRAMMAR",
    questionText: "雨が_____そうですから、傘を持って出かけましょう。",
    options: ["降り", "降る", "降った", "降って"],
    correctOption: 0,
    explanation: "様態を表す「〜そうだ（今にも〜しそう）」の前は動詞のマス形語幹（降り）になります。",
    marks: 2,
  },
  {
    id: "q8",
    category: "GRAMMAR",
    questionText: "先生、この本を_____いただけませんか。",
    options: ["貸して", "借りて", "貸した", "借りた"],
    correctOption: 0,
    explanation: "相手に貸してもらう依頼表現は「貸していただけませんか」です。",
    marks: 2,
  },
  {
    id: "q9",
    category: "GRAMMAR",
    questionText: "試験に合格する_____、毎日３時間復習しています。",
    options: ["ために", "ように", "から", "ので"],
    correctOption: 0,
    explanation: "意志的・意図的な目的を表す表現には名詞・動詞辞書形＋「ために」を用います。",
    marks: 2,
  },
  {
    id: "q10",
    category: "GRAMMAR",
    questionText: "テレビを_____まま寝てしまいました。",
    options: ["つけた", "つける", "つけ", "つけて"],
    correctOption: 0,
    explanation: "状態がそのまま続いていることを表す「〜まま」の前は過去形「た形」になります。",
    marks: 2,
  },
  {
    id: "q11",
    category: "PARTICLES",
    questionText: "財布を忘れましたが、友達_____お金を借りて助かりました。",
    options: ["から", "まで", "へ", "より"],
    correctOption: 0,
    explanation: "借りる相手（出所）を表す助詞には「から」（または「に」）が使われます。",
    marks: 2,
  },
  {
    id: "q12",
    category: "PARTICLES",
    questionText: "バスに乗る_____、５分ほど待ちました。",
    options: ["のに", "ので", "のを", "のが"],
    correctOption: 0,
    explanation: "目的「〜するのに（時間・費用がかかる）」を表す構文です。",
    marks: 2,
  },
  {
    id: "q13",
    category: "PARTICLES",
    questionText: "これ以上食べられません。もう一口_____無理です。",
    options: ["でも", "しか", "さえ", "ほど"],
    correctOption: 0,
    explanation: "「もう一口でも」は最小限の例示を示して否定的な結論を強調します。",
    marks: 2,
  },
  {
    id: "q14",
    category: "READING",
    questionText: "【敬語表現】お客様に対して「見てください」と丁寧に言う表現はどれですか？",
    options: ["ご覧ください", "拝見してください", "見せてください", "お見えになります"],
    correctOption: 0,
    explanation: "「見る」の相手の動作に対する尊敬語は「ご覧になる」で、「ご覧ください」となります。",
    marks: 2,
  },
  {
    id: "q15",
    category: "READING",
    questionText: "【短文理解】「駅前のスーパーは夜10時まで開いています。ただし、日曜日だけは夜8時に閉まります。」 日曜日の夜9時に買い物はできますか？",
    options: ["できない", "できる", "朝ならできる", "電話すればできる"],
    correctOption: 0,
    explanation: "日曜日は夜8時に閉まるため、夜9時には買い物はできません。",
    marks: 2,
  },
];

const N3_QUESTIONS: HomeworkQuestion[] = [
  {
    id: "q1",
    category: "KANJI",
    questionText: "「規則」の読み方として正しいものはどれですか？",
    options: ["きそく", "きぞく", "ぎそく", "ぎぞく"],
    correctOption: 0,
    explanation: "「規則」は「きそく」と読みます。",
    marks: 2,
  },
  {
    id: "q2",
    category: "KANJI",
    questionText: "「解決」の正しい読み方はどれですか？",
    options: ["かいけつ", "かいけち", "がいけつ", "かいせつ"],
    correctOption: 0,
    explanation: "問題などを処理する「解決」は「かいけつ」と読みます。",
    marks: 2,
  },
  {
    id: "q3",
    category: "KANJI",
    questionText: "「複雑」の対義語（反対語）にあたる漢字表記はどれですか？",
    options: ["単純", "平易", "簡略", "容易"],
    correctOption: 0,
    explanation: "「複雑（ふくざつ）」の直接的な対義語は「単純（たんじゅん）」です。",
    marks: 2,
  },
  {
    id: "q4",
    category: "VOCABULARY",
    questionText: "仕事が多すぎて、締め切りに間に合わない_____がある。",
    options: ["おそれ", "おかげ", "つもり", "わけ"],
    correctOption: 0,
    explanation: "望ましくない事態が起こる危険性を述べる表現は「〜おそれがある」です。",
    marks: 2,
  },
  {
    id: "q5",
    category: "VOCABULARY",
    questionText: "長い時間待たされて、とうとう_____が切れた。",
    options: ["我慢の限界", "気", "手", "足"],
    correctOption: 0,
    explanation: "堪忍袋の緒が切れる、あるいは我慢が限界に達することを「しびれを切らす」や「我慢の限界」と表現します。",
    marks: 2,
  },
  {
    id: "q6",
    category: "VOCABULARY",
    questionText: "プレゼンの準備を_____行っておいたので、本番もうまくいった。",
    options: ["入念に", "無駄に", "急激に", "勝手に"],
    correctOption: 0,
    explanation: "細部まで丁寧に行う様子を表す語は「入念に（にゅうねんに）」です。",
    marks: 2,
  },
  {
    id: "q7",
    category: "GRAMMAR",
    questionText: "天気予報に_____、今夜から大雨になる見込みです。",
    options: ["よると", "すれば", "ついて", "とって"],
    correctOption: 0,
    explanation: "伝聞の情報源を示す文型は「〜によると」です。",
    marks: 2,
  },
  {
    id: "q8",
    category: "GRAMMAR",
    questionText: "どれほど練習した_____、本番では緊張してしまうことがある。",
    options: ["としても", "わりに", "反面", "次第で"],
    correctOption: 0,
    explanation: "「どれほど〜としても（逆接の仮定・譲歩）」構文です。",
    marks: 2,
  },
  {
    id: "q9",
    category: "GRAMMAR",
    questionText: "健康の_____、エレベーターを使わずに階段を使うようにしている。",
    options: ["ために", "せいで", "くせに", "とおり"],
    correctOption: 0,
    explanation: "利益や目標のための目的を表す「名詞 ＋ のために」です。",
    marks: 2,
  },
  {
    id: "q10",
    category: "GRAMMAR",
    questionText: "この機械は使い方を間違えると、故障する_____があります。",
    options: ["おそれ", "はず", "わけ", "べき"],
    correctOption: 0,
    explanation: "悪い結果が生じる可能性を示す「〜おそれがある」を用います。",
    marks: 2,
  },
  {
    id: "q11",
    category: "PARTICLES",
    questionText: "彼は学生_____、すでに起業して会社を経営している。",
    options: ["でありながら", "にとって", "について", "にかけて"],
    correctOption: 0,
    explanation: "「〜でありながら」は立場や状態と矛盾する事実を表す逆接表現です。",
    marks: 2,
  },
  {
    id: "q12",
    category: "PARTICLES",
    questionText: "この地域の気候は、北日本_____雪が多く降る傾向にある。",
    options: ["ほど", "ばかり", "さえ", "きり"],
    correctOption: 0,
    explanation: "程度を比較する基準を示す助詞「ほど」が適切です。",
    marks: 2,
  },
  {
    id: "q13",
    category: "PARTICLES",
    questionText: "朝から晩_____ずっとパソコンに向かって作業を続けた。",
    options: ["まで", "にかけて", "にわたって", "として"],
    correctOption: 0,
    explanation: "「朝から晩まで」が明確な終点を示して最も自然です。",
    marks: 2,
  },
  {
    id: "q14",
    category: "READING",
    questionText: "【敬語選択】自分が作成した書類を上司に提出する際、添える言葉として最も適切なものはどれですか？",
    options: [
      "こちらが作成いたしました資料でございます。ご確認ください。",
      "こちらが作成された資料です。ご拝見ください。",
      "こちらをご覧になって作った資料です。",
      "こちらの資料をお読みさせてください。"
    ],
    correctOption: 0,
    explanation: "自らの動作を謙譲（作成いたしました）にし、相手に「ご確認ください」と促すのが正しいビジネス敬語です。",
    marks: 2,
  },
  {
    id: "q15",
    category: "READING",
    questionText: "【論理展開】「確かに電子書籍は手軽で便利だ。しかし、紙の書籍が持つ質感や手触りも読書体験には欠かせない。」 筆者が真に言いたいことは何ですか？",
    options: [
      "紙の書籍にも代えがたい独自の価値があるということ",
      "電子書籍は不便だから廃止すべきだということ",
      "読書は電子書籍だけに限定するべきだということ",
      "紙の書籍のほうが必ず安く購入できるということ"
    ],
    correctOption: 0,
    explanation: "「しかし」以降で紙の書籍ならではの魅力と重要性を強調しています。",
    marks: 2,
  },
];

const N2_QUESTIONS: HomeworkQuestion[] = [
  {
    id: "q1",
    category: "KANJI",
    questionText: "「把握」の正しい読み方はどれですか？",
    options: ["はあく", "はそく", "ばあく", "わあく"],
    correctOption: 0,
    explanation: "状況などを正しくつかむことを「把握（はあく）」と読みます。",
    marks: 2,
  },
  {
    id: "q2",
    category: "KANJI",
    questionText: "「顕著」の読み方を選びなさい。",
    options: ["けんちょ", "けんしょ", "げんちょ", "かんちょ"],
    correctOption: 0,
    explanation: "際立って目立つことを「顕著（けんちょ）」と読みます。",
    marks: 2,
  },
  {
    id: "q3",
    category: "KANJI",
    questionText: "「矛盾」の意味として正しいものはどれですか？",
    options: [
      "二つの事柄のつじつまが合わないこと",
      "相手の意見を尊重すること",
      "目標に向かって努力すること",
      "古い習慣を守り続けること"
    ],
    correctOption: 0,
    explanation: "「矛盾（むじゅん）」は前後のつじつまが合わず対立している状態を指します。",
    marks: 2,
  },
  {
    id: "q4",
    category: "VOCABULARY",
    questionText: "新技術の導入に伴い、作業効率が_____向上した。",
    options: ["飛躍的に", "あやふやに", "おおざっぱに", "やんわりと"],
    correctOption: 0,
    explanation: "急速に大きく進歩・向上する様子を「飛躍的（ひやくてき）に」と言います。",
    marks: 2,
  },
  {
    id: "q5",
    category: "VOCABULARY",
    questionText: "会議で反対意見が出たが、最終的には全員の意見を_____合意に至った。",
    options: ["すり合わせて", "食い違って", "見落として", "聞き流して"],
    correctOption: 0,
    explanation: "互いの違いを調整して一致させる動作を「すり合わせる」と言います。",
    marks: 2,
  },
  {
    id: "q6",
    category: "VOCABULARY",
    questionText: "突発的なトラブルにも、担当者は_____対処した。",
    options: ["臨機応変に", "前代未聞に", "一網打尽に", "十人十色に"],
    correctOption: 0,
    explanation: "その場の状況の変化に応じて適切に行動することを「臨機応変（りんきおうへん）に」と言います。",
    marks: 2,
  },
  {
    id: "q7",
    category: "GRAMMAR",
    questionText: "たとえ失敗に_____、全力を尽くしたことに後悔はない。",
    options: ["終わろうとも", "終わるにつれて", "終わるどころか", "終わるまいか"],
    correctOption: 0,
    explanation: "「たとえ〜ようとも（〜ても関係なく）」の強い決意を表す逆接仮定構文です。",
    marks: 2,
  },
  {
    id: "q8",
    category: "GRAMMAR",
    questionText: "プロの音楽家_____、毎日何時間もの基礎練習を怠らない。",
    options: ["たるもの", "ばかりか", "に即して", "にかこつけて"],
    correctOption: 0,
    explanation: "「〜たるもの（〜という資格や立場にある者は当然）」の規範表現です。",
    marks: 2,
  },
  {
    id: "q9",
    category: "GRAMMAR",
    questionText: "最新の調査結果に_____、プロジェクト計画の再検討が行われた。",
    options: ["基づいて", "かかわらず", "おいては", "限らず"],
    correctOption: 0,
    explanation: "基準や根拠とする事柄を示す「〜に基づいて」が適切です。",
    marks: 2,
  },
  {
    id: "q10",
    category: "GRAMMAR",
    questionText: "彼が犯行に関与していたとは、到底信じ_____。",
    options: ["がたい", "かねない", "ざるを得ない", "っこない"],
    correctOption: 0,
    explanation: "心理的にそうすることが非常に困難である表現は「動詞語幹 ＋ がたい」です。",
    marks: 2,
  },
  {
    id: "q11",
    category: "PARTICLES",
    questionText: "今回のプロジェクト成功は、チーム全員の協力_____してはあり得なかった。",
    options: ["なく", "あり", "とも", "より"],
    correctOption: 0,
    explanation: "条件を示す「〜なくしては（〜がなければ実現しない）」の文型です。",
    marks: 2,
  },
  {
    id: "q12",
    category: "PARTICLES",
    questionText: "一度決意した_____、途中で投げ出すわけにはいかない。",
    options: ["からには", "ものの", "どころか", "わりに"],
    correctOption: 0,
    explanation: "事実を踏まえて強い義務や意志を導く「〜からには」を用います。",
    marks: 2,
  },
  {
    id: "q13",
    category: "PARTICLES",
    questionText: "あの誠実な彼のこと_____、決して約束を破るようなことはしないはずだ。",
    options: ["だから", "なのに", "ゆえに", "にして"],
    correctOption: 0,
    explanation: "人の性格や特徴を理由として確信を述べる「〜のことだから」です。",
    marks: 2,
  },
  {
    id: "q14",
    category: "READING",
    questionText: "【ビジネス敬語】社外の取引先に対して、自社の上司（部長）の不在を伝える言葉として正しいものはどれですか？",
    options: [
      "申し訳ございません。部長の佐藤はただいま席を外しております。",
      "申し訳ございません。佐藤部長様はただいま席を外していらっしゃいます。",
      "申し訳ございません。佐藤様は席にいらっしゃいません。",
      "申し訳ございません。部長様は外出されております。"
    ],
    correctOption: 0,
    explanation: "社外の人に対して社内の人間を呼ぶ際は役職に「様」を付けず、呼び捨て（部長の佐藤）にして謙譲語を用います。",
    marks: 2,
  },
  {
    id: "q15",
    category: "READING",
    questionText: "【論説文の主旨】「効率化を過度に追求するあまり、試行錯誤や無駄から生まれる偶然の発見（セレンディピティ）が失われつつある。」 筆者の懸念は何ですか？",
    options: [
      "過度な効率重視によって創造的な発見の機会が損なわれていること",
      "効率化を推進する技術をもっと開発すべきだということ",
      "偶然の発見は科学的価値が全くないということ",
      "すべての作業は効率化すべきだということ"
    ],
    correctOption: 0,
    explanation: "「過度な効率追求」の弊害として「偶然の発見が失われる」ことを懸念しています。",
    marks: 2,
  },
];

const N1_QUESTIONS: HomeworkQuestion[] = [
  {
    id: "q1",
    category: "KANJI",
    questionText: "「脆弱」の正しい読み方はどれですか？",
    options: ["ぜいじゃく", "きじゃく", "さいじゃく", "そじゃく"],
    correctOption: 0,
    explanation: "もろくて弱いことを「脆弱（ぜいじゃく）」と読みます。",
    marks: 2,
  },
  {
    id: "q2",
    category: "KANJI",
    questionText: "「諮問」の正しい読み方はどれですか？",
    options: ["しもん", "しも", "ずもん", "じもん"],
    correctOption: 0,
    explanation: "意見を尋ね求めることを「諮問（しもん）」と読みます。",
    marks: 2,
  },
  {
    id: "q3",
    category: "KANJI",
    questionText: "「逡巡」の意味として最も適切なものはどれですか？",
    options: [
      "決断をためらってぐずぐずすること",
      "勢いよく前進すること",
      "素早く判断を下すこと",
      "他人の過ちを寛大に許すこと"
    ],
    correctOption: 0,
    explanation: "「逡巡（しゅんじゅん）」はためらい躊躇することを意味します。",
    marks: 2,
  },
  {
    id: "q4",
    category: "VOCABULARY",
    questionText: "彼の突拍子もない発言に、会議の出席者は全員_____に暮れた。",
    options: ["途方", "見当", "都合", "思惑"],
    correctOption: 0,
    explanation: "どうしていいか分からず困り果てる慣用句は「途方に暮れる（とほうにくれる）」です。",
    marks: 2,
  },
  {
    id: "q5",
    category: "VOCABULARY",
    questionText: "長年の研究成果がようやく認められ、学会で_____を浴びた。",
    options: ["脚光", "月光", "日光", "蛍光"],
    correctOption: 0,
    explanation: "世間の注目の的になることを「脚光（きゃっこう）を浴びる」と言います。",
    marks: 2,
  },
  {
    id: "q6",
    category: "VOCABULARY",
    questionText: "双方の意見は完全に平行線をたどり、妥協の余地は_____なかった。",
    options: ["毛頭", "露骨に", "甚だ", "強いて"],
    correctOption: 0,
    explanation: "下に打ち消しを伴って「少しも〜ない」を強調する副詞は「毛頭（もうとう）ない」です。",
    marks: 2,
  },
  {
    id: "q7",
    category: "GRAMMAR",
    questionText: "未曾有の危機に直面した今、国民一人ひとりの連帯が_____。",
    options: ["求められてやまない", "求められるきらいがある", "求められる極みだ", "求められてならない"],
    correctOption: 0,
    explanation: "「〜てやまない」は心の底から強く願ったり求めたりする気持ちを表す最上級の文型です。",
    marks: 2,
  },
  {
    id: "q8",
    category: "GRAMMAR",
    questionText: "最高責任者の立場にある者として、この不正を見過ごす_____。",
    options: ["わけにはいかない", "ことになっている", "までもない", "に越したことはない"],
    correctOption: 0,
    explanation: "社会的責任や倫理上許されないことを表す「〜わけにはいかない」が妥当です。",
    marks: 2,
  },
  {
    id: "q9",
    category: "GRAMMAR",
    questionText: "法改正の是非をめぐり、有識者の間でも議論が_____。",
    options: ["紛糾を極めている", "紛糾に堪えない", "紛糾にかまけている", "紛糾に及んでいる"],
    correctOption: 0,
    explanation: "極限状態を表す「〜を極める（紛糾を極める）」が最も自然なコロケーションです。",
    marks: 2,
  },
  {
    id: "q10",
    category: "GRAMMAR",
    questionText: "いくら多忙を極めようとも、健康管理を怠る_____。",
    options: ["べからず", "まじきことだ", "に堪えない", "を禁じ得ない"],
    correctOption: 1,
    explanation: "「〜まじき（〜てはならない当然の道義）」を表します。",
    marks: 2,
  },
  {
    id: "q11",
    category: "PARTICLES",
    questionText: "長年の鍛錬_____して、この卓越した技術の体得は不可能であった。",
    options: ["なく", "あり", "こそ", "のみ"],
    correctOption: 0,
    explanation: "「〜なくして（〜がなくては）」という不可欠の条件文です。",
    marks: 2,
  },
  {
    id: "q12",
    category: "PARTICLES",
    questionText: "彼ほどの博識な人物_____、この古代文字の解読には難航した。",
    options: ["にして", "にあって", "を限りに", "を契機に"],
    correctOption: 0,
    explanation: "高水準の人物を挙げて「〜ほどの者でさえ」を格調高く表す「〜にして」です。",
    marks: 2,
  },
  {
    id: "q13",
    category: "PARTICLES",
    questionText: "一度公言した_____、いかなる批判を受けようとも最後まで責任を全うする。",
    options: ["以上は", "ばかりに", "反面", "にひきかえ"],
    correctOption: 0,
    explanation: "前提事実に基づき強い覚悟を示す「〜以上は」です。",
    marks: 2,
  },
  {
    id: "q14",
    category: "READING",
    questionText: "【文脈把握】「AIが高度な意思決定を代替し得る現代において、人間に真に問われるのは『正解を導く力』ではなく『何を問題と設定すべきかを見極める構想力』である。」 筆者が最も強調している人間の本質的役割は何ですか？",
    options: [
      "課題そのものを発見し定義する力（課題設定力）",
      "既存の正解をAIより素早く計算する演算速度",
      "AIの判断に無批判に従う順応性",
      "あらゆる問題を技術的自動化に委ねること"
    ],
    correctOption: 0,
    explanation: "「何が問題かを見極める構想力」が人間に真に問われると明確に述べています。",
    marks: 2,
  },
  {
    id: "q15",
    category: "READING",
    questionText: "【高等論説文】「伝統とは過去の遺物を静態的に保存することではなく、時代の変容に応じて絶えず再解釈と創造的破壊を繰り返す動態的プロセスに他ならない。」 筆者による『伝統』の定義はどれですか？",
    options: [
      "時代の変化に合わせて常に再解釈し更新し続ける動的な営み",
      "過去の形式を一切変えずにそのまま保存する硬直的な行為",
      "古い文化遺産をすべて廃棄して新しいものだけを追うこと",
      "一度確立された価値観を未来永劫変えないこと"
    ],
    correctOption: 0,
    explanation: "「絶えず再解釈と創造的破壊を繰り返す動態的プロセス」という記述と合致しています。",
    marks: 2,
  },
];

export function getFallbackQuestionsForLevel(courseLevel: string, studentSalt: string): HomeworkQuestion[] {
  let baseQuestions = N5_QUESTIONS;
  if (courseLevel === "N1") baseQuestions = N1_QUESTIONS;
  else if (courseLevel === "N2") baseQuestions = N2_QUESTIONS;
  else if (courseLevel === "N3") baseQuestions = N3_QUESTIONS;
  else if (courseLevel === "N4") baseQuestions = N4_QUESTIONS;

  // Clone and add student-specific individualized salt tags to guarantee anti-collusion uniqueness
  return baseQuestions.map((q, idx) => ({
    ...q,
    id: `q${idx + 1}`,
    questionText: `【第${idx + 1}問 • 個別コード #${studentSalt}】 ${q.questionText}`,
  }));
}
